# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
- group: Database Variables

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool: my Agent Pool
        steps:
        - task: DockerCompose@0
          inputs:
            dockerComposeFile: '**/docker-compose.yml'
            dockerComposeFileArgs: |
              SA_PASSWORD=$(SA_PASSWORD)
            action: 'Run a Docker Compose command'
            dockerComposeCommand: 'build'