FROM node:lts-alpine

WORKDIR /app
COPY ./app/package.json /app/package.json
COPY ./app/package-lock.json /app/package-lock.json

ENV NODE_ENV=development
RUN npm install

COPY ./app/ /app

ARG PORT=80
ENV PORT=${PORT}
EXPOSE ${PORT}

CMD ["npm", "run", "serve"]
