CREATE DATABASE [app]
GO

USE [app]
GO

DROP TABLE [FC001_TODO]
GO

CREATE TABLE [FC001_TODO] (
	TODO_ID INT NOT NULL IDENTITY(0,1) PRIMARY KEY,
	NAME_NM NVARCHAR(255),
	PRIORITY_AMT INT
)
GO

INSERT INTO [FC001_TODO] 
	(NAME_NM, PRIORITY_AMT)
VALUES 
	('Groceries', 3),
	('Pick up kids', 1),
	('Mow the lawn', 4),
	('Visit dentist', 2)
GO

CREATE PROCEDURE SP_TODO_CREATE
(@name NVARCHAR(255), @priority INT)
AS
	INSERT INTO [FC001_TODO] (NAME_NM, PRIORITY_AMT)
	VALUES (@name, @priority)
GO

CREATE PROCEDURE SP_TODO_DELETE
(@id INT) 
AS
	DELETE FROM [FC001_TODO]
	WHERE [TODO_ID] = @id
GO

CREATE PROCEDURE SP_TODO_UPDATE
(@id INT, @name NVARCHAR(255), @priority INT) 
AS
	UPDATE [FC001_TODO]
	SET NAME_NM = @name,
		PRIORITY_AMT = @priority
	WHERE TODO_ID = @id
GO



